### ISSUE TITLE
Notifications for paused medications

### ISSUE THREAD

**Issue by lascimmia** [AdamGuidarini/MediTrak#130]
Even though a medication is paused, and there are no pending recurrences in the calendar, notifications keep popping up and I can't delete them.

**Comment by AdamGuidarini** [comment]
Thanks for reporting this, shouldn't be too difficult to fix

**Comment by Foxtrek64** [comment]
May be related, maybe not, but I am seeing a similar behavior for modifying time with a schedule. I had a reminder for the morning that I moved to the evening and now I get alerted at both the original and new times. I did not apply the change retroactively.

**Comment by AdamGuidarini** [comment]
I think it is related, when you don't check "apply retroactively" the app actually creates a new medication as a "child" of the previous version and marks the previous version as inactive. When you do apply retroactively it just overwrites the existing medication with the new data. I have it partly fixed in my working branch. Just need to do more testing and I think there are a couple improvements  I can make. I should have time tomorrow (and if needed Friday)

**Comment by AdamGuidarini** [comment]
Just released version 0.13.3 with the fix for this issue. 

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.13.3

I'll close this issue, but if you're still getting those extra notifications let me know and I can reopen it.
