### ISSUE TITLE
Chose different doses - feature request

### ISSUE THREAD

**Issue by avipars** [AdamGuidarini/MediTrak#81]
For example if I took 2 advice pills today at 9 am bur then at 4 pm took 1... it would be nice to be able to change/set dosage amount per each time taken (and maybe have a default dose if the user doesn't make a selection)

**Comment by AdamGuidarini** [comment]
I can definitely see that being useful. I'm having a bit of a hard time imagining it though. My first thought is to add the option modify the dosage taken in the dose info dialog (the one that shows up when you tap the "i" icon in the schedule). I could then use that to display instead of the default dosage in the schedule and dosage history.

Would that fit what you're looking for?

**Comment by avipars** [comment]
That would be amazing. I use the app daily as is and this would be awesome 👌 


Thank you for developing it in the first place.

**Comment by AdamGuidarini** [comment]
I'm glad you like it! I'm working on some improvements for notifications currently, but I've added this to my to do list for the app. I also made the changes to the database schema that I think I'll need to implement it in my current branch. 

Thank you for the suggestion!

**Comment by AdamGuidarini** [comment]
Just released it in version [0.12.5](https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.12.5)
